const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const agentId = url.searchParams.get('agentId');
    const position = url.searchParams.get('position') || 'bottom-right';

    // Build widget script using string concatenation to avoid template literal nesting
    let widgetScript = '(function() {\n';
    widgetScript += '  "use strict";\n';
    widgetScript += '  \n';
    widgetScript += '  if (window.ChatPopWidget) {\n';
    widgetScript += '    console.log("ChatPop widget already loaded");\n';
    widgetScript += '    return;\n';
    widgetScript += '  }\n';
    widgetScript += '\n';
    widgetScript += '  const agentId = "' + agentId + '";\n';
    widgetScript += '  const position = "' + position + '";\n';
    widgetScript += '  const supabaseUrl = "https://etwjtxqjcwyxdamlcorf.supabase.co";\n';
    widgetScript += '  const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0d2p0eHFqY3d5eGRhbWxjb3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzI3MTcsImV4cCI6MjA2ODk0ODcxN30.Dji_q0KFNL8hetK_Og8k9MI4l8sZJ5iCQQxQc4j1isM";\n';
    widgetScript += '  const chatUrl = "https://etwjtxqjcwyxdamlcorf.supabase.co/functions/v1/public-chat?agentId=" + agentId;\n';
    widgetScript += '\n';
    widgetScript += '  // Viewport detection\n';
    widgetScript += '  const isMobile = () => window.innerWidth < 768;\n';
    widgetScript += '  const isTablet = () => window.innerWidth >= 768 && window.innerWidth < 1024;\n';
    widgetScript += '\n';
  widgetScript += '  let conversationId = null;\n';
  widgetScript += '  let isOpen = false;\n';
  widgetScript += '  let isLoading = false;\n';
  widgetScript += '  let messageCount = 0;\n';
  widgetScript += '  let leadCaptured = false;\n';
  widgetScript += '  let leadConfig = null;\n';
  widgetScript += '  let widget, overlay, agentData;\n';
  widgetScript += '  let sessionId = "session-" + Date.now() + "-" + Math.random().toString(36).substr(2, 9);\n';
    widgetScript += '\n';
    widgetScript += '  // Instead of iframe, embed chat UI directly\n';
    widgetScript += '  window.ChatPopWidget = { open: () => toggleChat(), close: () => toggleChat() };\n';
    widgetScript += '\n';
    widgetScript += '  function adjustColorBrightness(hex, percent) {\n';
    widgetScript += '    const num = parseInt(hex.replace("#",""), 16);\n';
    widgetScript += '    const amt = Math.round(2.55 * percent);\n';
    widgetScript += '    const R = Math.min(255, Math.max(0, (num >> 16) + amt));\n';
    widgetScript += '    const G = Math.min(255, Math.max(0, (num >> 8 & 0x00FF) + amt));\n';
    widgetScript += '    const B = Math.min(255, Math.max(0, (num & 0x0000FF) + amt));\n';
    widgetScript += '    return "#" + (0x1000000 + R*0x10000 + G*0x100 + B).toString(16).slice(1);\n';
    widgetScript += '  }\n';
    widgetScript += '\n';
    widgetScript += '  function getAvatarUrl(data, isUser) {\n';
    widgetScript += '    if (isUser) {\n';
    widgetScript += '      const color = (data?.message_bubble_color || "#3B82F6").replace("#", "");\n';
    widgetScript += '      return "https://ui-avatars.com/api/?name=You&background=" + color + "&color=fff";\n';
    widgetScript += '    }\n';
    widgetScript += '    if (data?.profile_image_url) return data.profile_image_url;\n';
    widgetScript += '    const name = data?.name || "AI";\n';
    widgetScript += '    const color = (data?.message_bubble_color || "#3B82F6").replace("#", "");\n';
    widgetScript += '    return "https://ui-avatars.com/api/?name=" + encodeURIComponent(name) + "&background=" + color + "&color=fff";\n';
    widgetScript += '  }\n';
    widgetScript += '\n';
    widgetScript += '  function createWidget() {\n';
    widgetScript += '    widget = document.createElement("button");\n';
    widgetScript += '    widget.id = "chatpop-widget";\n';
    widgetScript += '    widget.innerHTML = "💬";\n';
    widgetScript += '    widget.style.cssText = "position:fixed;' + (position.includes('bottom') ? 'bottom:20px;' : 'top:20px;') + (position.includes('right') ? 'right:20px;' : 'left:20px;') + 'width:60px;height:60px;border-radius:50%;background:#84cc16;color:white;border:none;font-size:28px;cursor:pointer;box-shadow:0 4px 12px rgba(0,0,0,0.15);z-index:9999;transition:all 0.3s;";\n';
    widgetScript += '    widget.onclick = toggleChat;\n';
    widgetScript += '    document.body.appendChild(widget);\n';
    widgetScript += '    fetchAgentData().then(data => { if (data?.message_bubble_color) widget.style.background = data.message_bubble_color; });\n';
    widgetScript += '  }\n';
    widgetScript += '\n';
    widgetScript += '  function createOverlay(primaryColor, theme) {\n';
    widgetScript += '    const gradientEnd = adjustColorBrightness(primaryColor, -20);\n';
    widgetScript += '    overlay = document.createElement("div");\n';
    widgetScript += '    \n';
    widgetScript += '    function updateOverlayStyles() {\n';
    widgetScript += '      overlay.style.cssText = "position:fixed;" + (isMobile() ? "right:0;left:0;bottom:0;top:0;width:100%;height:100%;border-radius:0;" : "' + (position.includes('bottom') ? 'bottom:0;' : 'top:0;') + (position.includes('right') ? 'right:0;' : 'left:0;') + 'width:" + (isTablet() ? "420px" : "400px") + ";height:" + (isTablet() ? "620px" : "600px") + ";border-radius:16px;") + "background:white;box-shadow:-4px 0 40px rgba(0,0,0,0.15);z-index:9998;display:" + (overlay?.style.display === \\"block\\" ? \\"block\\" : \\"none\\") + ";overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;";\n';
    widgetScript += '    }\n';
    widgetScript += '    \n';
    widgetScript += '    updateOverlayStyles();\n';
    widgetScript += '    overlay.innerHTML = \'<div style="display:flex;flex-direction:column;height:100%;background:linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);">\' +\n';
    widgetScript += '      (isMobile() ? \'<button onclick="window.ChatPopWidget.close()" style="position:absolute;top:20px;right:20px;background:rgba(0,0,0,0.3);border:none;color:white;width:40px;height:40px;border-radius:50%;font-size:24px;cursor:pointer;z-index:10;display:flex;align-items:center;justify-content:center;backdrop-filter:blur(5px);">×</button>\' : \'\') +\n';
    widgetScript += '      \'<div style="background:linear-gradient(135deg, \' + primaryColor + \' 0%, \' + gradientEnd + \' 100%);color:white;padding:20px;display:flex;align-items:center;gap:12px;"><img id="agent-avatar" style="width:48px;height:48px;border-radius:50%;border:3px solid white;" src="\' + getAvatarUrl(agentData, false) + \'"><div><h2 id="agent-name" style="margin:0;font-size:18px;">\' + (agentData?.name || "AI Assistant") + \'</h2><p style="margin:0;font-size:13px;opacity:0.9;">AI Assistant</p></div></div>\' +\n';
    widgetScript += '      \'<div id="messages" style="flex:1;overflow-y:auto;padding:20px;"></div>\' +\n';
    widgetScript += '      \'<div style="padding:16px;background:white;border-top:1px solid #e5e7eb;"><div style="display:flex;gap:8px;"><input id="chat-input" type="text" placeholder="Type your message..." style="flex:1;padding:12px;border:2px solid #e5e7eb;border-radius:12px;font-size:14px;outline:none;color:#1f2937 !important;background:#ffffff;-webkit-text-fill-color:#1f2937;"/><button id="send-btn" style="padding:12px 24px;background:\' + primaryColor + \';color:white;border:none;border-radius:12px;cursor:pointer;font-weight:600;">Send</button></div></div>\' +\n';
    widgetScript += '      \'<div style="text-align:center;padding:12px;font-size:11px;color:#9ca3af;">Powered by ChatPop</div></div>\';\n';
    widgetScript += '    overlay.dataset.primaryColor = primaryColor;\n';
    widgetScript += '    document.body.appendChild(overlay);\n';
    widgetScript += '    document.getElementById("send-btn").onclick = sendMessage;\n';
    widgetScript += '    document.getElementById("chat-input").onkeypress = (e) => { if (e.key === "Enter") sendMessage(); };\n';
    widgetScript += '    if (agentData?.initial_message) addMessage(agentData.initial_message, false);\n';
    widgetScript += '    \n';
    widgetScript += '    // Add viewport resize handler\n';
    widgetScript += '    let resizeTimeout;\n';
    widgetScript += '    window.addEventListener("resize", () => {\n';
    widgetScript += '      clearTimeout(resizeTimeout);\n';
    widgetScript += '      resizeTimeout = setTimeout(() => {\n';
    widgetScript += '        if (overlay && isOpen) {\n';
    widgetScript += '          updateOverlayStyles();\n';
    widgetScript += '        }\n';
    widgetScript += '      }, 150);\n';
    widgetScript += '    });\n';
    widgetScript += '  }\n';
    widgetScript += '\n';
    widgetScript += '  function toggleChat() {\n';
    widgetScript += '    isOpen = !isOpen;\n';
    widgetScript += '    if (isOpen && !overlay) {\n';
    widgetScript += '      fetchAgentData().then(data => {\n';
    widgetScript += '        agentData = data;\n';
    widgetScript += '        const primaryColor = data?.message_bubble_color || "#3B82F6";\n';
    widgetScript += '        const theme = data?.chat_interface_theme || "dark";\n';
    widgetScript += '        createOverlay(primaryColor, theme);\n';
    widgetScript += '        overlay.style.display = "block";\n';
    widgetScript += '      });\n';
    widgetScript += '    } else if (overlay) {\n';
    widgetScript += '      overlay.style.display = isOpen ? "block" : "none";\n';
    widgetScript += '    }\n';
    widgetScript += '  }\n';
    widgetScript += '\n';
  widgetScript += '  async function fetchAgentData() {\n';
  widgetScript += '    try {\n';
  widgetScript += '      const configRes = await fetch(supabaseUrl + "/functions/v1/get-widget-config?agentId=" + agentId, { headers: { "apikey": supabaseKey } });\n';
  widgetScript += '      if (configRes.ok) { const configData = await configRes.json(); if (configData.agent?.lead_capture_config) leadConfig = configData.agent.lead_capture_config; }\n';
  widgetScript += '      const response = await fetch(supabaseUrl + "/rest/v1/rpc/get_public_agent_data?agent_uuid=" + agentId, { headers: { "apikey": supabaseKey, "Content-Type": "application/json" } });\n';
  widgetScript += '      if (response.ok) { const data = await response.json(); if (data && data.length > 0) { agentData = data[0]; checkProactiveLeadCapture(); return agentData; } }\n';
  widgetScript += '    } catch (error) { console.error("Error fetching agent:", error); }\n';
  widgetScript += '    return null;\n';
  widgetScript += '  }\n';
    widgetScript += '\n';
  widgetScript += '  function addMessage(content, isUser) {\n';
  widgetScript += '    const messages = document.getElementById("messages");\n';
  widgetScript += '    if (!messages) return;\n';
  widgetScript += '    const div = document.createElement("div");\n';
  widgetScript += '    div.style.cssText = "margin-bottom:16px;display:flex;gap:12px;align-items:flex-start;" + (isUser ? "flex-direction:row-reverse;" : "");\n';
  widgetScript += '    const avatar = document.createElement("img");\n';
  widgetScript += '    avatar.src = getAvatarUrl(agentData, isUser);\n';
  widgetScript += '    avatar.style.cssText = "width:32px;height:32px;border-radius:50%;";\n';
  widgetScript += '    const messageDiv = document.createElement("div");\n';
  widgetScript += '    messageDiv.textContent = content;\n';
  widgetScript += '    messageDiv.style.cssText = "padding:12px 16px;border-radius:16px;max-width:70%;word-wrap:break-word;background:" + (isUser ? (overlay?.dataset?.primaryColor || "#3B82F6") : "#f3f4f6") + ";color:" + (isUser ? "white" : "#1f2937") + ";";\n';
  widgetScript += '    div.appendChild(avatar);\n';
  widgetScript += '    div.appendChild(messageDiv);\n';
  widgetScript += '    messages.appendChild(div);\n';
  widgetScript += '    messages.scrollTop = messages.scrollHeight;\n';
  widgetScript += '    if (isUser) { messageCount++; checkProactiveLeadCapture(); }\n';
  widgetScript += '  }\n';
    widgetScript += '\n';
  widgetScript += '  function checkProactiveLeadCapture() {\n';
  widgetScript += '    if (!leadConfig || !leadConfig.enabled || leadCaptured) return;\n';
  widgetScript += '    const triggerType = leadConfig.trigger_type || "ai_detection";\n';
  widgetScript += '    if (triggerType === "immediate" && messageCount === 0) {\n';
  widgetScript += '      renderLeadCaptureForm({ prompt: leadConfig.prompt, fields: leadConfig.fields, button_text: leadConfig.button_text });\n';
  widgetScript += '    } else if (triggerType === "after_messages" && messageCount >= (leadConfig.trigger_after_messages || 2)) {\n';
  widgetScript += '      renderLeadCaptureForm({ prompt: leadConfig.prompt, fields: leadConfig.fields, button_text: leadConfig.button_text });\n';
  widgetScript += '    }\n';
  widgetScript += '  }\n';
  widgetScript += '\n';
  widgetScript += '  function renderLeadCaptureForm(actionData) {\n';
  widgetScript += '    if (leadCaptured) return;\n';
    widgetScript += '    const formDiv = document.createElement("div");\n';
    widgetScript += '    formDiv.style.cssText = "background:#f8fafc;padding:16px;border-radius:12px;margin-top:8px;";\n';
    widgetScript += '    let formHTML = \'<div style="margin-bottom:12px;"><p style="margin:0 0 12px 0;font-weight:600;color:#1f2937;">\' + (actionData.prompt || "Please share your information") + \'</p>\';\n';
    widgetScript += '    actionData.fields.forEach(field => {\n';
    widgetScript += '      formHTML += \'<div style="margin-bottom:12px;"><label style="display:block;margin-bottom:4px;font-size:13px;color:#4b5563;">\' + field.label + (field.required ? \' *\' : \'\') + \'</label>\';\n';
    widgetScript += '      if (field.type === "textarea") {\n';
    widgetScript += '        formHTML += \'<textarea id="lead-\' + field.key + \'" placeholder="\' + field.placeholder + \'" style="width:100%;padding:8px;border:1px solid #d1d5db;border-radius:6px;font-size:14px;color:#1f2937;" rows="3"></textarea>\';\n';
    widgetScript += '      } else if (field.type === "select") {\n';
    widgetScript += '        formHTML += \'<select id="lead-\' + field.key + \'" style="width:100%;padding:8px;border:1px solid #d1d5db;border-radius:6px;font-size:14px;color:#1f2937;">\';\n';
    widgetScript += '        formHTML += \'<option value="">\' + field.placeholder + \'</option>\';\n';
    widgetScript += '        if (field.options) field.options.forEach(opt => { formHTML += \'<option value="\' + opt + \'">\' + opt + \'</option>\'; });\n';
    widgetScript += '        formHTML += \'</select>\';\n';
    widgetScript += '      } else {\n';
    widgetScript += '        formHTML += \'<input type="\' + field.type + \'" id="lead-\' + field.key + \'" placeholder="\' + field.placeholder + \'" style="width:100%;padding:8px;border:1px solid #d1d5db;border-radius:6px;font-size:14px;color:#1f2937;" />\';\n';
    widgetScript += '      }\n';
    widgetScript += '      formHTML += \'</div>\';\n';
    widgetScript += '    });\n';
    widgetScript += '    formHTML += \'<button id="submit-lead-btn" style="width:100%;padding:10px;background:\' + (overlay?.dataset?.primaryColor || "#3B82F6") + \';color:white;border:none;border-radius:8px;cursor:pointer;font-weight:600;">\' + (actionData.button_text || "Submit") + \'</button></div>\';\n';
    widgetScript += '    formDiv.innerHTML = formHTML;\n';
    widgetScript += '    document.getElementById("messages").appendChild(formDiv);\n';
    widgetScript += '    document.getElementById("submit-lead-btn").onclick = () => handleLeadSubmit(actionData.fields, actionData.success_message);\n';
    widgetScript += '  }\n';
    widgetScript += '\n';
  widgetScript += '  async function handleLeadSubmit(fields, successMessage) {\n';
  widgetScript += '    const leadData = {};\n';
  widgetScript += '    let hasError = false;\n';
  widgetScript += '    fields.forEach(field => {\n';
  widgetScript += '      const input = document.getElementById("lead-" + field.key);\n';
  widgetScript += '      const value = input?.value.trim();\n';
  widgetScript += '      if (field.required && !value) { hasError = true; input.style.borderColor = "#ef4444"; return; }\n';
  widgetScript += '      if (value) leadData[field.key] = value;\n';
  widgetScript += '    });\n';
  widgetScript += '    if (hasError) { addMessage("Please fill in all required fields.", false); return; }\n';
  widgetScript += '    setLoading(true);\n';
  widgetScript += '    try {\n';
  widgetScript += '      const response = await fetch(supabaseUrl + "/functions/v1/capture-lead", { method: "POST", headers: { "Content-Type": "application/json", "apikey": supabaseKey }, body: JSON.stringify({ agentId, conversationId, leadData }) });\n';
  widgetScript += '      if (!response.ok) throw new Error("Failed to submit");\n';
  widgetScript += '      const data = await response.json();\n';
  widgetScript += '      leadCaptured = true;\n';
  widgetScript += '      addMessage(successMessage || leadConfig?.success_message || data.message || "Thank you! We will be in touch soon.", false);\n';
  widgetScript += '      document.getElementById("submit-lead-btn").disabled = true;\n';
  widgetScript += '      document.getElementById("submit-lead-btn").textContent = "Submitted!";\n';
  widgetScript += '    } catch (error) { console.error("Lead submit error:", error); addMessage("Sorry, there was an error submitting your information.", false); }\n';
  widgetScript += '    finally { setLoading(false); }\n';
  widgetScript += '  }\n';
    widgetScript += '\n';
    widgetScript += '  function setLoading(loading) {\n';
    widgetScript += '    isLoading = loading;\n';
    widgetScript += '    const input = document.getElementById("chat-input");\n';
    widgetScript += '    const btn = document.getElementById("send-btn");\n';
    widgetScript += '    if (input) input.disabled = loading;\n';
    widgetScript += '    if (btn) { btn.disabled = loading; btn.style.opacity = loading ? "0.6" : "1"; }\n';
    widgetScript += '  }\n';
    widgetScript += '\n';
    widgetScript += '  async function sendMessage() {\n';
    widgetScript += '    const input = document.getElementById("chat-input");\n';
    widgetScript += '    const message = input?.value.trim();\n';
    widgetScript += '    if (!message || isLoading) return;\n';
    widgetScript += '    addMessage(message, true);\n';
    widgetScript += '    input.value = "";\n';
    widgetScript += '    setLoading(true);\n';
    widgetScript += '    try {\n';
    widgetScript += '      const response = await fetch(supabaseUrl + "/functions/v1/chat-completion", { method: "POST", headers: { "Content-Type": "application/json", "apikey": supabaseKey }, body: JSON.stringify({ agentId, message, conversationId, sessionId }) });\n';
    widgetScript += '      if (!response.ok) throw new Error("Failed to send message");\n';
    widgetScript += '      const data = await response.json();\n';
    widgetScript += '      if (!conversationId && data.conversationId) conversationId = data.conversationId;\n';
    widgetScript += '      if (data.message) addMessage(data.message, false);\n';
    widgetScript += '      if (data.actions && data.actions.length > 0) {\n';
    widgetScript += '        data.actions.forEach(action => {\n';
    widgetScript += '          if (action.type === "lead_capture") renderLeadCaptureForm(action.data);\n';
    widgetScript += '        });\n';
    widgetScript += '      }\n';
    widgetScript += '    } catch (error) { console.error("Error:", error); addMessage("Sorry, I encountered an error. Please try again.", false); }\n';
    widgetScript += '    finally { setLoading(false); }\n';
    widgetScript += '  }\n';
    widgetScript += '\n';
    widgetScript += '  if (document.readyState === "loading") { document.addEventListener("DOMContentLoaded", createWidget); } else { createWidget(); }\n';
    widgetScript += '})();';

    return new Response(widgetScript, {
      headers: { ...corsHeaders, 'Content-Type': 'application/javascript' }
    });

  } catch (error) {
    console.error('Error serving enhanced chat widget:', error);
    return new Response('Internal server error', {
      status: 500,
      headers: corsHeaders
    });
  }
});
